name: Update Videos
on:
  workflow_dispatch:

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
      - name: Install dependencies
        run: pnpm install
      - name: Run update:videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          JM_PASSPHRASE: ${{ secrets.JM_PASSPHRASE }}
        run: pnpm run update:videos jm
